const uebungen = [
    {
      id: 1,
      name: "Kniebeugen",
      sets: 3,
      repetitions: 10,
      weight: 60, 
      muscleGroups: ["Beine", "Po"], 
      description: "Eine Grundübung für die Beinmuskulatur.",
    },
    {
      id: 2,
      name: "Liegestütze",
      sets: 3,
      repetitions: 15,
      muscleGroups: ["Brust", "Schultern", "Trizeps"], 
      description: "Eine klassische Übung für den Oberkörper.",
    },
    {
      id: 3,
      name: "Rudern",
      sets: 3,
      repetitions: 12,
      weight: 50, 
      muscleGroups: ["Rücken", "Bizeps"], 
      description: "Eine Übung für den Rücken und die Arme.",
    },
    {
      id: 4,
      name: "Ausfallschritte",
      sets: 3,
      repetitions: 10,
      legSide: "links", 
      muscleGroups: ["Beine", "Po"], 
      description: "Eine Variation der Kniebeuge für mehr Balance.",
    },
    {
      id: 5,
      name: "Plank",
      duration: "30 Sekunden",
      sets: 3,
      muscleGroups: ["Bauch", "Rücken", "Schultern"],
      description: "Eine statische Übung zur Stärkung des Rumpfes.",
    },
    {
      id: 6,
      name: "Dips",
      sets: 3,
      repetitions: 10,
      muscleGroups: ["Brust", "Schultern", "Trizeps"], 
      description: "Eine anspruchsvolle Übung für den Oberkörper.",
    },
    {
      id: 7,
      name: "Klimmzüge",
      sets: 3,
      repetitions: "so viele wie möglich",
      muscleGroups: ["Rücken", "Bizeps"], 
      description: "Eine der besten Übungen für den Rücken.",
    },
    {
      id: 8,
      name: "Crunches",
      sets: 3,
      repetitions: 20,
      muscleGroups: ["Bauch"], 
      description: "Eine Übung für die Bauchmuskulatur.",
    },
    {
      id: 9,
      name: "Wadenheben",
      sets: 3,
      repetitions: 15,
      muscleGroups: ["Waden"], 
      description: "Eine Übung für die Wadenmuskulatur.",
    },
  ];